### ISSUE TITLE
Integrate with SQLite

### ISSUE THREAD

**Issue by Zifius** [Zifius/telegram-knowledgebase-bot#4]
- [ ] Create DB schema to store term, its definition, user who created / last updated the definition, channel name
- [x] Store definitions / update them

**Comment by Zifius** [comment]
@frostygrizzly @Romanow88 are we good with first checkbox?

**Comment by Zifius** [comment]
Looks good to me, but probably parent_id here https://github.com/Zifius/telegram-knowledgebase-bot/blob/master/model.py#L27 should be updated to something like user_id to make it clearer?

**Comment by alexandra-trisch** [comment]
should be fixed by #26
