### ISSUE TITLE
Hide/reduce list output

### ISSUE THREAD

**Issue by robodenitro** [Zifius/telegram-knowledgebase-bot#47]
The output of the **/list** command might be huge (imagine we have about hundred terms) and annoying. 

1. A single response with a bunch of terms occupies a chat screen (or even several pages), it makes user experience worse - users have to scroll down such messages
2. Regular chat users might suffer from repetitive unusable info

Two options:
- Send response to private chat between user and bot
- Add pagination (actually doesn't help in case 2)

**Comment by alexandra-trisch** [comment]
I'm not sure bot can send message to the user without prior acknowledgement from user.

**Comment by Romanow88** [comment]
I think the user needs to do a /start command for that to be allowed.

**Comment by Romanow88** [comment]
possible solution - full text search or terms and definitions, and / or asking the user to join to a private chatt.
